### ISSUE TITLE
[Image       ] Error loading texture data/images/image-loading.gif

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/PyWallet#101]
https://sentry.io/andre-5t/pywallet/issues/393849343/

```
[Image       ] Error loading texture data/images/image-loading.gif
```

**Comment by AndreMiras** [comment]
https://sentry.io/andre-5t/pywallet/issues/394191337/

**Comment by AndreMiras** [comment]
This is currently only happening on Android.
I could find the root cause by updating `Image.texture_update()` removing the generic except block. Here is the exception I got:
```
10-28 14:58:55.528  5610  6007 I python  : [INFO   ] [GL          ] NPOT texture support is available
10-28 14:58:55.772  5610  6007 I python  :  Traceback (most recent call last):
10-28 14:58:55.772  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/app/main.py", line 1581, in <module>
10-28 14:58:55.772  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/app/main.py", line 1575, in <module>
10-28 14:58:55.773  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivy/app.py", line 802, in run
10-28 14:58:55.773  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivy/app.py", line 599, in load_kv
10-28 14:58:55.773  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivy/lang/builder.py", line 301, in load_file
10-28 14:58:55.774  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivy/lang/builder.py", line 350, in load_string
10-28 14:58:55.774  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivy/lang/parser.py", line 393, in __init__
10-28 14:58:55.774  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivy/lang/parser.py", line 499, in parse
10-28 14:58:55.774  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivy/lang/parser.py", line 463, in execute_directives
10-28 14:58:55.775  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivymd/tabs.py", line 186, in <module>
10-28 14:58:55.775  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivymd/tabs.py", line 189, in MDTabHeader
10-28 14:58:55.775  5610  6007 I python  :    File "/home/andre/Progz/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivy/metrics.py", line 136, in dp
10-28 14:58:55.776  5610  6007 I python  :    File "kivy/properties.pyx", line 291, in kivy.properties.dpi2px (kivy/properties.c:2939)
10-28 14:58:55.776  5610  6007 I python  :    File "kivy/properties.pyx", line 299, in kivy.properties.dpi2px (kivy/properties.c:2646)
10-28 14:58:55.776  5610  6007 I python  :  TypeError: float() argument must be a string or a number
10-28 14:58:55.876  5610  6007 I python  : Python for android ended.
10-28 14:58:56.006  6031  6031 F DEBUG   :     #00 pc 000c009a  /data/app/com.github.andremiras.pywallet-1/lib/arm/libpython2.7.so (PyThreadState_New+93)
10-28 14:58:56.006  6031  6031 F DEBUG   :     #01 pc 000ca3d5  /data/app/com.github.andremiras.pywallet-1/lib/arm/libpython2.7.so (PyThread_acquire_lock+76)
```
So the problem seems to come from `kivymd`, `MDTabHeader` class. And I believe was fixed here:
https://gitlab.com/kivymd/KivyMD/commit/e81c02afbca915a4d71c85d3486f6710b53df2c1
