### ISSUE TITLE
_libsecp256k1.so is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/PyWallet#11]
I had this issue trying to run on Android:
`buildozer android adb -- logcat | grep -i python`
```
06-13 00:24:19.182 17873 18089 I python  :  Traceback (most recent call last):
06-13 00:24:19.182 17873 18089 I python  :    File "/home/ubuntu/workspace/PyWallet/.buildozer/android/app/main.py", line 16, in <module>
06-13 00:24:19.183 17873 18089 I python  :    File "/home/ubuntu/workspace/PyWallet/.buildozer/android/app/pywalib.py", line 7, in <module>
06-13 00:24:19.184 17873 18089 I python  :    File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/devp2p/app.py", line 8, in <module>
06-13 00:24:19.185 17873 18089 I python  :    File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/devp2p/crypto.py", line 32, in <module>
06-13 00:24:19.186 17873 18089 I python  :    File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/secp256k1/__init__.py", line 5, in <module>
06-13 00:24:19.186 17873 18089 I python  :  ImportError: dlopen failed: "/data/data/org.test.pywallet/files/app/lib/python2.7/site-packages/secp256k1/_libsecp256k1.so" is 64-bit instead of 32-bit
06-13 00:24:19.272 17873 18089 I python  : Python for android ended.
```

**Comment by AndreMiras** [comment]
both libsecp256k1 and secp256k1 recipes compiles now, but we have a new runtime error
```
06-16 22:01:00.449 20940 21112 I python  :  Traceback (most recent call last):
06-16 22:01:00.450 20940 21112 I python  :    File "/home/ubuntu/workspace/PyWallet/.buildozer/android/app/main.py", line 16, in <module>
06-16 22:01:00.450 20940 21112 I python  :    File "/home/ubuntu/workspace/PyWallet/.buildozer/android/app/pywalib.py", line 7, in <module>
06-16 22:01:00.451 20940 21112 I python  :    File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/devp2p/app.py", line 8, in <module>
06-16 22:01:00.451 20940 21112 I python  :    File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/devp2p/crypto.py", line 32, in <module>
06-16 22:01:00.452 20940 21112 I python  :    File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/secp256k1/__init__.py", line 5, in <module>
06-16 22:01:00.452 20940 21112 I python  :  ImportError: dlopen failed: cannot locate symbol "PyExc_TypeError" referenced by "/data/data/org.test.pywallet/files/app/lib/python2.7/site-packages/secp256k1/_libsecp256k1.so"...
06-16 22:01:00.521 20940 21112 I python  : Python for android ended.
```
Closing and opening a new dedicated ticket.
