### ISSUE TITLE
Flaky helper_test_empty_account() UI test

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/PyWallet#110]
In Travis `helper_test_empty_account()` fails quite often, see trace below:
```
======================================================================
FAIL: test_ui_base (test_ui_base.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/ui/test_ui_base.py", line 522, in test_ui_base
    app.run()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/app.py", line 828, in run
    runTouchApp()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/base.py", line 339, in idle
    Clock.tick()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
    self._process_events()
  File "kivy/_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-OEEiKf/Kivy/kivy/_clock.c:7700)
  File "kivy/_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-OEEiKf/Kivy/kivy/_clock.c:7577)
  File "kivy/_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-OEEiKf/Kivy/kivy/_clock.c:7498)
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (/tmp/pip-build-OEEiKf/Kivy/kivy/_clock.c:3483)
  File "src/tests/ui/test_ui_base.py", line 500, in run_test
    self.helper_test_empty_account(app)
  File "src/tests/ui/test_ui_base.py", line 49, in helper_test_empty_account
    self.assertEqual(len(dialogs), 1)
AssertionError: 0 != 1
----------------------------------------------------------------------
Ran 1 test in 1.113s
FAILED (failures=1)
Ran 1 test in 2.338s
1 FAILED TEST!
The command "(eval "$SCRIPT_COMMAND")" exited with 1.
Done. Your build exited with 1.
```

**Comment by AndreMiras** [comment]
Still failing after last fix attempt, see trace below:
```
======================================================================
| test_ui_base                                                   LOG |
======================================================================
[INFO   ] [Logger      ] Record log in /home/travis/.kivy/logs/kivy_17-11-13_3.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]
[INFO   ] [KivyMD      ] KivyMD version: 0.1.2
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Clipboard   ] Provider: xclip(['clipboard_dbusklipper', 'clipboard_gtk3'] ignored)
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
Xlib:  extension "RANDR" missing on display ":99.0".
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <2.1 Mesa 10.1.3>
[INFO   ] [GL          ] OpenGL vendor <VMware, Inc.>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on llvmpipe (LLVM 3.4, 256 bits)>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
 INFO:accounts	searching for key files directory=/tmp/tmp2eWF9p
 WARNING:accounts	no accounts found 
 INFO:app	registering service service=accounts
[INFO   ] [Base        ] Start application main loop
[WARNING] [MDBottomNavigation] 50dp is less than the minimum size of 80dp for a MDBottomNavigationItem. We must now expand to 168dp.
[WARNING] [MDBottomNavigation] 33dp is less than the minimum size of 80dp for a MDBottomNavigationItem. We must now expand to 168dp.
[INFO   ] [Base        ] Leaving application in progress...
======================================================================
FAIL: test_ui_base (test_ui_base.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/ui/test_ui_base.py", line 529, in test_ui_base
    app.run()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/app.py", line 828, in run
    runTouchApp()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 663, in mainloop
    self._mainloop()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 405, in _mainloop
    EventLoop.idle()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/base.py", line 339, in idle
    Clock.tick()
  File "/home/travis/build/AndreMiras/PyWallet/venv/local/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
    self._process_events()
  File "kivy/_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-BSKE7C/Kivy/kivy/_clock.c:7700)
  File "kivy/_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-BSKE7C/Kivy/kivy/_clock.c:7577)
  File "kivy/_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (/tmp/pip-build-BSKE7C/Kivy/kivy/_clock.c:7498)
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (/tmp/pip-build-BSKE7C/Kivy/kivy/_clock.c:3483)
  File "src/tests/ui/test_ui_base.py", line 507, in run_test
    self.helper_test_empty_account(app)
  File "src/tests/ui/test_ui_base.py", line 56, in helper_test_empty_account
    self.assertEqual(len(dialogs), 1)
AssertionError: 0 != 1
----------------------------------------------------------------------
Ran 1 test in 2.585s
FAILED (failures=1)
Ran 1 test in 3.881s
1 FAILED TEST!
The command "(eval "$SCRIPT_COMMAND")" exited with 1.
Done. Your build exited with 1.
```

**Comment by AndreMiras** [comment]
Conversation with KeyWeeUsr on IRC (freenode kivy-dev).
> AndreMiras KeyWeeUsr[m]: in my tests it seems that I sometimes run in a race condition where I trigger a widget events and except another widget to be in some states.
> AndreMiras but the other widget may not be in that state yet. How do you give the UI time to render the state between after one event? I guess it's somewhat related to `Clock.schedule_interval()` and the pause method.
> AndreMiras But I'm wondering if there's a way to kinda: trigger(); wait_more_this_time(); assert state
> KeyWeeUsr[m] inherit from GraphicUnitTest and use advance_frames() :)
> KeyWeeUsr[m] or... call EventLoop.idle() in a for loop, that's behind it
> KeyWeeUsr[m] I call advance together with Clock.max_fps (or Config, not sure where the value is public)
