### ISSUE TITLE
JavaException: JVM exception occurred: Fail to connect to camera service

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/PyWallet#129]
https://sentry.io/andre-5t/pywallet/issues/418307749/

```
JavaException: JVM exception occurred: Fail to connect to camera service
(32 additional frame(s) were not displayed)
...
  File "home/andre/workspace/PyWallet/.buildozer/android/platform/build/dists/pywallet/private/lib/python2.7/site-packages/kivy/core/camera/camera_android.py", line 49, in init_camera
  File "jnius/jnius_export_class.pxi", line 906, in jnius.jnius.JavaMultipleMethod.__call__ (jnius/jnius.c:27877)
  File "jnius/jnius_export_class.pxi", line 637, in jnius.jnius.JavaMethod.__call__ (jnius/jnius.c:24248)
  File "jnius/jnius_export_class.pxi", line 803, in jnius.jnius.JavaMethod.call_staticmethod (jnius/jnius.c:26273)
  File "jnius/jnius_utils.pxi", line 93, in jnius.jnius.check_exception (jnius/jnius.c:3872)

JavaException: JVM exception occurred: Fail to connect to camera service
```

**Comment by robertpro** [comment]
Hey @AndreMiras did you find the resolution for this issue?

**Comment by AndreMiras** [comment]
Hey glad you're using the project. Well I saw this error in Sentry, but I could't reproduce myself back then.
Are you able to reproduce this issue everytime and it's once in the while? Because if it's easy for you to reproduce then I can ping you once I've updated. What's your device and OS version by the way?

Anyway this project needs to be updated to recent python-for-android changes as well as to Python3. Also a lot of other deps in the Ethereum stack will need to be updated.
I'll start working on this pretty soon and hopefully this error will vanish.

**Comment by robertpro** [comment]
Hey, I am sorry, I am not using this project hehe. I was testing the camera on my project, and looks good on Linux, but when I tried to run it on Android, it failed, googling the error, bring me up to here

**Comment by AndreMiras** [comment]
Well that may still help to know which device you have. And also if you could share the stacktrace

**Comment by robertpro** [comment]
OS: Android 8.1.0
Python: 3.7.1
Kivy: 1.11.0.dev0 (master branch, Pipy version - 1.10.1 - was having an error with opencv4)

Code (from [here](https://kivy.org/doc/stable/examples/gen__camera__main__py.html#)):

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
import time
Builder.load_string('''
<CameraClick>:
    orientation: 'vertical'
    Camera:
        id: camera
        resolution: (640, 480)
        play: False
    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
    Button:
        text: 'Capture'
        size_hint_y: None
        height: '48dp'
        on_press: root.capture()
''')


class CameraClick(BoxLayout):
    def capture(self):
        '''
        Function to capture the images and give them the names
        according to their captured time and date.
        '''
        camera = self.ids['camera']
        timestr = time.strftime("%Y%m%d_%H%M%S")
        camera.export_to_png("IMG_{}.png".format(timestr))
        print("Captured")


class TestCamera(App):

    def build(self):
        return CameraClick()


TestCamera().run()
```

Trace

```
03-20 15:48:49.920 25026 25042 V python  : extracting _python_bundle/modules/_bisect.cpython-37m.so
03-20 15:48:49.987 25026 25050 I python  : Initializing Python for Android
03-20 15:48:49.987 25026 25050 I python  : Setting additional env vars from p4a_env_vars.txt
03-20 15:48:49.987 25026 25050 I python  : Changing directory to the one provided by ANDROID_ARGUMENT
03-20 15:48:49.987 25026 25050 I python  : /data/user/0/org.anti.test_drawer/files/app
03-20 15:48:49.989 25026 25050 I python  : Preparing to initialize python
03-20 15:48:49.990 25026 25050 I python  : _python_bundle dir exists
03-20 15:48:49.990 25026 25050 I python  : calculated paths to be...
03-20 15:48:49.990 25026 25050 I python  : /data/user/0/org.anti.test_drawer/files/app/_python_bundle/stdlib.zip:/data/user/0/org.anti.test_drawer/files/app/_python_bundle/modules
03-20 15:48:49.990 25026 25050 I python  : set wchar paths...
03-20 15:48:50.025 25026 25050 I python  : Initialized python
03-20 15:48:50.025 25026 25050 I python  : AND: Init threads
03-20 15:48:50.026 25026 25050 I python  : testing python print redirection
03-20 15:48:50.027 25026 25050 I python  : Android path ['.', '/data/user/0/org.anti.test_drawer/files/app/_python_bundle/stdlib.zip', '/data/user/0/org.anti.test_drawer/files/app/_python_bundle/modules', '/data/user/0/org.anti.test_drawer/files/app/_python_bundle/site-packages']
03-20 15:48:50.027 25026 25050 I python  : os.environ is environ({'PATH': '/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin', 'DOWNLOAD_CACHE': '/data/cache', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'BOOTCLASSPATH': '/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/bouncycastle.jar:/system/framework/apache-xml.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.hidl.base-V1.0-java.jar:/system/framework/android.hidl.manager-V1.0-java.jar:/system/framework/framework-oahl-backward-compatibility.jar:/system/framework/android.test.base.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/com.android.location.provider.jar', 'ANDROID_SOCKET_zygote': '11', 'ANDROID_ENTRYPOINT': 'main.pyc', 'ANDROID_ARGUMENT': '/data/user/0/org.anti.test_drawer/files/app', 'ANDROID_APP_PATH': '/data/user/0/org.anti.test_drawer/files/app', 'ANDROID_PRIVATE': '/data/user/0/org.anti.test_drawer/files', 'ANDROID_UNPACK': '/data/user/0/org.anti.test_drawer/files/app', 'PYTHONHOME': '/data/user/0/org.anti.test_drawer/files/app', 'PYTHONPATH': '/data/user/0/org.anti.test_drawer/files/app:/data/user/0/org.anti.test_drawer/files/app/lib', 'PYTHONOPTIMIZE': '2', 'P4A_BOOTSTRAP': 'SDL2', 'PYTHON_NAME': 'python', 'P4A_IS_WINDOWED': 'True', 'P4A_ORIENTATION': 'portrait', 'P4A_NUMERIC_VERSION': 'None', 'P4A_MINSDK': '21', 'LC_CTYPE': 'C.UTF-8'})
03-20 15:48:50.027 25026 25050 I python  : Android kivy bootstrap done. __name__ is __main__
03-20 15:48:50.027 25026 25050 I python  : AND: Ran string
03-20 15:48:50.027 25026 25050 I python  : Run user program, change dir and execute entrypoint
03-20 15:48:50.086 25026 25050 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 21)
03-20 15:48:50.086 25026 25050 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
03-20 15:48:50.088 25026 25050 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.anti.test_drawer/files/app/.kivy/logs/kivy_19-03-20_0.txt
03-20 15:48:50.089 25026 25050 I python  : [INFO   ] [Kivy        ] v1.11.0.dev0, git-Unknown, 20190318
03-20 15:48:50.089 25026 25050 I python  : [INFO   ] [Python      ] v3.7.1 (default, Mar 17 2019, 22:58:45) 
03-20 15:48:50.089 25026 25050 I python  : [Clang 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55
03-20 15:48:50.119 25026 25050 I python  : [INFO   ] [Factory     ] 184 symbols loaded
03-20 15:48:50.239 25026 25050 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
03-20 15:48:50.272 25026 25050 I python  : [INFO   ] [Window      ] Provider: sdl2
03-20 15:48:50.310 25026 25050 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
03-20 15:48:50.311 25026 25050 I python  : [INFO   ] [GL          ] Backend used <sdl2>
03-20 15:48:50.311 25026 25050 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 (4.5 (Core Profile) Mesa 18.3.4)'>
03-20 15:48:50.311 25026 25050 I python  : [INFO   ] [GL          ] OpenGL vendor <b'Google (Intel Open Source Technology Center)'>
03-20 15:48:50.312 25026 25050 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Android Emulator OpenGL ES Translator (Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) )'>
03-20 15:48:50.312 25026 25050 I python  : [INFO   ] [GL          ] OpenGL parsed version: 2, 0
03-20 15:48:50.313 25026 25050 I python  : [INFO   ] [GL          ] Texture max size <16384>
03-20 15:48:50.314 25026 25050 I python  : [INFO   ] [GL          ] Texture max units <32>
03-20 15:48:50.337 25026 25050 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
03-20 15:48:50.338 25026 25050 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
03-20 15:48:50.392 25026 25050 I python  : [INFO   ] [Camera      ] Provider: android
03-20 15:48:50.397 25026 25050 I python  : [INFO   ] [Text        ] Provider: sdl2
03-20 15:48:50.523 25026 25050 I python  :  Traceback (most recent call last):
03-20 15:48:50.523 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/lang/builder.py", line 623, in _apply_rule
03-20 15:48:50.523 25026 25050 I python  :    File "kivy/weakproxy.pyx", line 33, in kivy.weakproxy.WeakProxy.__setattr__
03-20 15:48:50.523 25026 25050 I python  :    File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
03-20 15:48:50.523 25026 25050 I python  :    File "kivy/properties.pyx", line 817, in kivy.properties.ListProperty.set
03-20 15:48:50.524 25026 25050 I python  :    File "kivy/properties.pyx", line 524, in kivy.properties.Property.set
03-20 15:48:50.524 25026 25050 I python  :    File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch
03-20 15:48:50.524 25026 25050 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
03-20 15:48:50.524 25026 25050 I python  :    File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
03-20 15:48:50.524 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/uix/camera.py", line 103, in _on_index
03-20 15:48:50.524 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/core/camera/camera_android.py", line 42, in __init__
03-20 15:48:50.524 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/core/camera/__init__.py", line 70, in __init__
03-20 15:48:50.524 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/core/camera/camera_android.py", line 49, in init_camera
03-20 15:48:50.524 25026 25050 I python  :    File "jnius/jnius_export_class.pxi", line 1044, in jnius.jnius.JavaMultipleMethod.__call__
03-20 15:48:50.525 25026 25050 I python  :    File "jnius/jnius_export_class.pxi", line 765, in jnius.jnius.JavaMethod.__call__
03-20 15:48:50.525 25026 25050 I python  :    File "jnius/jnius_export_class.pxi", line 931, in jnius.jnius.JavaMethod.call_staticmethod
03-20 15:48:50.525 25026 25050 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
03-20 15:48:50.525 25026 25050 I python  :  jnius.jnius.JavaException: JVM exception occurred: Fail to connect to camera service
03-20 15:48:50.525 25026 25050 I python  :  
03-20 15:48:50.525 25026 25050 I python  :  During handling of the above exception, another exception occurred:
03-20 15:48:50.525 25026 25050 I python  :  
03-20 15:48:50.525 25026 25050 I python  :  Traceback (most recent call last):
03-20 15:48:50.525 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/app/main.py", line 127, in <module>
03-20 15:48:50.526 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/app.py", line 829, in run
03-20 15:48:50.526 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/app/main.py", line 124, in build
03-20 15:48:50.526 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/uix/boxlayout.py", line 131, in __init__
03-20 15:48:50.526 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/uix/layout.py", line 76, in __init__
03-20 15:48:50.527 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/uix/widget.py", line 348, in __init__
03-20 15:48:50.527 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/lang/builder.py", line 469, in apply
03-20 15:48:50.527 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/lang/builder.py", line 630, in _apply_rule
03-20 15:48:50.527 25026 25050 I python  :  kivy.lang.builder.BuilderException: Parser: File "<inline>", line 6:
03-20 15:48:50.527 25026 25050 I python  :  ...
03-20 15:48:50.527 25026 25050 I python  :        4:    Camera:
03-20 15:48:50.527 25026 25050 I python  :        5:        id: camera
03-20 15:48:50.527 25026 25050 I python  :  >>    6:        resolution: (640, 480)
03-20 15:48:50.527 25026 25050 I python  :        7:        play: False
03-20 15:48:50.528 25026 25050 I python  :        8:    ToggleButton:
03-20 15:48:50.528 25026 25050 I python  :  ...
03-20 15:48:50.528 25026 25050 I python  :  JavaException: JVM exception occurred: Fail to connect to camera service
03-20 15:48:50.528 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/lang/builder.py", line 623, in _apply_rule
03-20 15:48:50.528 25026 25050 I python  :    File "kivy/weakproxy.pyx", line 33, in kivy.weakproxy.WeakProxy.__setattr__
03-20 15:48:50.528 25026 25050 I python  :    File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
03-20 15:48:50.528 25026 25050 I python  :    File "kivy/properties.pyx", line 817, in kivy.properties.ListProperty.set
03-20 15:48:50.528 25026 25050 I python  :    File "kivy/properties.pyx", line 524, in kivy.properties.Property.set
03-20 15:48:50.528 25026 25050 I python  :    File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch
03-20 15:48:50.528 25026 25050 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
03-20 15:48:50.528 25026 25050 I python  :    File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
03-20 15:48:50.528 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/uix/camera.py", line 103, in _on_index
03-20 15:48:50.529 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/core/camera/camera_android.py", line 42, in __init__
03-20 15:48:50.529 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/core/camera/__init__.py", line 70, in __init__
03-20 15:48:50.529 25026 25050 I python  :    File "/home/roberto/dev/tools/android/buildozer/android/platform/build/build/python-installs/test_drawer/kivy/core/camera/camera_android.py", line 49, in init_camera
03-20 15:48:50.529 25026 25050 I python  :    File "jnius/jnius_export_class.pxi", line 1044, in jnius.jnius.JavaMultipleMethod.__call__
03-20 15:48:50.529 25026 25050 I python  :    File "jnius/jnius_export_class.pxi", line 765, in jnius.jnius.JavaMethod.__call__
03-20 15:48:50.529 25026 25050 I python  :    File "jnius/jnius_export_class.pxi", line 931, in jnius.jnius.JavaMethod.call_staticmethod
03-20 15:48:50.529 25026 25050 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
03-20 15:48:50.529 25026 25050 I python  :  
03-20 15:48:50.529 25026 25050 I python  : Python for android ended.
```

@AndreMiras thank you!

**Comment by robertpro** [comment]
I forgot to add the buildozer:

```
requirements = python3,kivy,plyer,android
android.permissions = CAMERA
```

**Comment by AndreMiras** [comment]
OK in this case it could be a runtime permission problem.
Look how it's being handled in zbarcam for instance https://github.com/kivy-garden/garden.zbarcam/blob/20190303/zbarcam/zbarcam.py#L73
If you need further help try on the Kivy support channel, you can ping me there directly

**Comment by robertpro** [comment]
Yeah, you right, I am copying the code just for the next newbie like me :D

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.utils import platform
import time

Builder.load_string('''
<CameraClick>:
    orientation: 'vertical'
    Camera:
        id: camera
        resolution: (640, 480)
        play: False
    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
    Button:
        text: 'Capture'
        size_hint_y: None
        height: '48dp'
        on_press: root.capture()
''')


class CameraClick(BoxLayout):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._request_android_permissions()

    @staticmethod
    def is_android():
        return platform == 'android'

    def _request_android_permissions(self):
        """
        Requests CAMERA permission on Android.
        """
        if not self.is_android():
            return
        from android.permissions import request_permission, Permission
        request_permission(Permission.CAMERA)

    def capture(self):
        '''
        Function to capture the images and give them the names
        according to their captured time and date.
        '''
        camera = self.ids['camera']
        timestr = time.strftime("%Y%m%d_%H%M%S")
        camera.export_to_png("IMG_{}.png".format(timestr))
        print("Captured")


class TestCamera(App):

    def build(self):
        return CameraClick()


TestCamera().run()
```

**Comment by fengboZ** [comment]
is this fixed? can the kivy camera run on android @AndreMiras

**Comment by AndreMiras** [comment]
Yes @fengboZ the Kivy camera runs on Android. I use it for [PyWallet](https://github.com/AndreMiras/PyWallet) and [EtherollApp](https://github.com/AndreMiras/EtherollApp) all through [zbarcam](https://github.com/kivy-garden/zbarcam)

**Comment by fengboZ** [comment]
I copied the code above and compiled it to an apk files, but it crashed after opening it on android..., I am new to kivy, wanna build an android application using kivy, my application basically needs to open up the camera and take a photo, and then the photo needs to be processed using detection library which will return a text back. and then the text will be stored on android, it needs to be later transferred into PC. can I complete these procedures with kivy? (just to confirm, if it can be done in kivy, I'll spend time on kivy)
thanks for you comments @AndreMiras

**Comment by pasteurjr** [comment]
Hello,
  I tried using android runtime permissions, as suggested by @AndreMiras, but buildozer logcat  returns the following error message:
   
     from virtualenv import main ImportError: cannot import name 'main'

Buildozer.spec :
requirements: python3, kivy, pyjnius
android.add_aars = support-compat-27.0.0.aar

main.py 

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from permissions.location import check_permission, ask_permission

class ExampleRoot(BoxLayout):

    def check_fine_location_permission(self):
        check_permission("android.permission.ACCESS_FINE_LOCATION")

    def request_fine_location_permission(self):
        ask_permission("android.permission.ACCESS_FINE_LOCATION")




class ExampleApp(App):
    def build(self):
        return ExampleRoot()

if __name__ == '__main__':
    ExampleApp().run()

permissions/location.py 

from jnius import autoclass
from kivy.logger import Logger

PythonActivity = autoclass("org.kivy.android.PythonActivity").mActivity
Context = autoclass('android.content.Context')
ContextCompat = autoclass('android.support.v4.content.ContextCompat')

def check_permission(permission, activity=PythonActivity):
    permission_status = ContextCompat.checkSelfPermission(activity,
                                                          permission)

    Logger.info(permission_status)
    permission_granted = 0 == permission_status
    Logger.info("Permission Status: {}".format(permission_granted))
    return permission_granted

def ask_permission(permission, activity=PythonActivity):
    PythonActivity.requestPermissions([permission])


Any suggestion to fix this error?

Thanks a lot

**Comment by Ham-Merhead** [comment]
> from virtualenv import main ImportError: cannot import name 'main'

try 

`pip3 install pip --upgrade  `

**Comment by fs-melo** [comment]
> Sim @fengboZ, a câmera Kivy é executada no Android. Eu o uso para [PyWallet](https://github.com/AndreMiras/PyWallet) e [EtherollApp](https://github.com/AndreMiras/EtherollApp) durante todo o [zbarcam](https://github.com/kivy-garden/zbarcam)

Hi @AndreMiras, what's Kivy and buildozer versions used to generate the apk file of zar am.

**Comment by AndreMiras** [comment]
It was probably the latest version back then. Also zbarcam (upstream) CI itself was using a specific version https://github.com/kivy-garden/zbarcam/blob/2019.1020/dockerfiles/Dockerfile-android#L20.
But I'll probably update both projects in the coming days so keep an eye on both repositories.
Also both projects will have their CI updated and will be submitted to F-Droid so you can study the reproducibility of the builds.
I'm closing this issue as it's old and being dragged in a different direction.

**Comment by roysomoza** [comment]
Hello everyone, I hope you can help me. I have the same problem JavaException: JVM exception occurred: Fail to connect to camera service. I see that the possible solution is to use android.permission. How can I install this library? Thank you so much

**Comment by RobertFlatt** [comment]
The android package is pre-installed in the generated apk/aab. It is not available on other platforms https://github.com/Android-for-Python/Android-for-Python-Users#the-android-package

The above posts are kinda old when measured in 'computer years'. A couple of general points: 

1) The runtime permissions code above must, on newer Android devices, be called after `on_start()` https://github.com/Android-for-Python/Android-for-Python-Users#user-permissions

2) Kivy Camera (and it's derivatives such as zbarcam) use a depreciated Android api. As an alternative consider https://github.com/Android-for-Python/Camera4Kivy there are some examples https://github.com/Android-for-Python/Camera4Kivy#examples

Support requests should be directed to the user groups https://discord.gg/NzawVYMe or      https://groups.google.com/g/kivy-users

**Comment by roysomoza** [comment]
Thank you very much for the immediate response, I am currently using a
device with OS 8.0, I thought that the solutions in that post could help. I
will study the options you have given me and join the Discord group.

If you allow me, I will write to you by this means in case I have any other
questions. I appreciate a lot your help

**Comment by RobertFlatt** [comment]
Best to ask in the user groups, asking me questions directly assumes I know the answer. And pretty much everything I know with any confidence is in the document I linked.
