### ISSUE TITLE
Various secp256k1 recipe issues

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/PyWallet#14]
I see at least 3 issues:

1. `hostpython setup.py install -O2` bad exit code
2. `autogen.sh: No such file or directory`
3. `Using bundled libsecp256k1` (from secp256k1 setup.py) when it should use the `libsecp256k1` recipe

See log below:
```
[INFO]:    Building secp256k1 for armeabi-v7a
[INFO]:    secp256k1 apparently isn't already in site-packages
[INFO]:    Building compiled components in secp256k1
[INFO]:    -> directory context /home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/build/other_builds/secp256k1/armeabi-v7a/secp256k1
[INFO]:    -> running hostpython setup.py build_ext -v
           working: Installed /home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/build/other_builds/secp256k1/armeabi-v7a/secp256k1/.eggs/pytest_runner-2.6.2-py2.7.egg                                                                                    
           working: creating build/lib.linux-x86_64-2.7                                                                                                                                                                                                       [INFO]:    ->
 running find build/lib.linux-x86_64-2.7 -name "*.o" -exec arm-linux-androideabi-strip --strip-unneeded {} ;
[INFO]:    <- directory context /home/ubuntu/workspace/PyWallet/.buildozer/android/platform/python-for-android-master
[INFO]:    Installing secp256k1 into site-packages
[INFO]:    -> directory context /home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/build/other_builds/secp256k1/armeabi-v7a/secp256k1
[INFO]:    -> running hostpython setup.py install -O2 --root=/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/build/python-installs/pywallet --install-lib=lib/python2.7/site-packages
           working: error: /home/ubuntu/workspace/PyWallet/.buildozer/andException in thread background thread for pid 25480:                                                                                                                                             
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_1: 

  RAN: /home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython2/hostpython setup.py install -O2 --root=/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/build/python-installs/pywallet --insta
ll-lib=lib/python2.7/site-packages

  STDOUT:
0.29.1
Using bundled libsecp256k1
running install
running build
running build_py
copying secp256k1/__main__.py -> build/lib.linux-x86_64-2.7/secp256k1
copying secp256k1/__init__.py -> build/lib.linux-x86_64-2.7/secp256k1
running build_clib
error: /home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/build/other_builds/secp256k1/armeabi-v7a/secp256k1/libsecp256k1/autogen.sh: No such file or directory


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 905, in <module>
    main()
  File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 902, in main
    ToolchainCL()
  File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 508, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 565, in build_recipes
  File "pythonforandroid/recipe.py", line 891, in build_arch
  File "pythonforandroid/recipe.py", line 859, in install_python_package
  File "pythonforandroid/logger.py", line 175, in shprint
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython2/hostpython setup.py install -O2 --root=/home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/build/python-installs/pywallet --insta
ll-lib=lib/python2.7/site-packages

  STDOUT:
0.29.1
Using bundled libsecp256k1
running install
running build
running build_py
copying secp256k1/__main__.py -> build/lib.linux-x86_64-2.7/secp256k1
copying secp256k1/__init__.py -> build/lib.linux-x86_64-2.7/secp256k1
running build_clib
error: /home/ubuntu/workspace/PyWallet/.buildozer/android/platform/build/build/other_builds/secp256k1/armeabi-v7a/secp256k1/libsecp256k1/autogen.sh: No such file or directory


  STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=pywallet --bootstrap=sdl2 --requirements=hostpython2,kivy,setuptools,openssl,pycryptodome,pysha3,ethash,scrypt,bitcoin,rlp,pyethereum,devp2p,gevent,pbkdf2,pyethapp,https://gitlab.com/k
ivymd/KivyMD/repository/archive.zip?ref=7de5790274a45c4fa2fb9c6fcd875645e536c95b,requests,pyelliptic==1.5.7,cffi,secp256k1 --arch armeabi-v7a --copy-libs --local-recipes /home/ubuntu/workspace/PyWallet/python-for-android/recipes --color=always --storage-dir=/home/ubu
ntu/workspace/PyWallet/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by AndreMiras** [comment]
Fixed with recent commits
