### ISSUE TITLE
OSError: Cannot load native module 'Crypto.Hash._BLAKE2s' (Travis)

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/PyWallet#30]
Travis can't install `pbkdf2` when `pycryptodome` is installed/
See build 86:
https://travis-ci.org/AndreMiras/PyWallet/builds/246657156

The error is:
```
[?25hCollecting PyYAML (from -r requirements.txt (line 1))
/home/travis/build/AndreMiras/PyWallet/.buildozer/android/platform/build/build/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached PyYAML-3.12.tar.gz
Collecting bitcoin (from -r requirements.txt (line 2))
  Using cached bitcoin-1.1.42.tar.gz
Collecting pbkdf2 (from -r requirements.txt (line 7))
  Using cached pbkdf2-1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jlmed6/pbkdf2/setup.py", line 11, in <module>
        from pbkdf2 import __version__
      File "pbkdf2.py", line 62, in <module>
        from Crypto.Hash import HMAC, SHA as SHA1
      File "/home/travis/build/AndreMiras/PyWallet/.buildozer/android/platform/build/build/python-installs/pywallet/lib/python2.7/site-packages/Crypto/Hash/HMAC.py", line 81, in <module>
        import MD5, BLAKE2s
      File "/home/travis/build/AndreMiras/PyWallet/.buildozer/android/platform/build/build/python-installs/pywallet/lib/python2.7/site-packages/Crypto/Hash/BLAKE2s.py", line 83, in <module>
        """)
      File "/home/travis/build/AndreMiras/PyWallet/.buildozer/android/platform/build/build/python-installs/pywallet/lib/python2.7/site-packages/Crypto/Util/_raw_api.py", line 171, in load_pycryptodome_raw_lib
        raise OSError("Cannot load native module '%s'" % name)
    OSError: Cannot load native module 'Crypto.Hash._BLAKE2s'
    
    ----------------------------------------
[31mCommand "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jlmed6/pbkdf2/[0m


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/travis/build/AndreMiras/PyWallet/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 905, in <module>
    main()
  File "/home/travis/build/AndreMiras/PyWallet/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 902, in main
    ToolchainCL()
  File "/home/travis/build/AndreMiras/PyWallet/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 508, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/travis/build/AndreMiras/PyWallet/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/travis/build/AndreMiras/PyWallet/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 190, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 585, in build_recipes
  File "pythonforandroid/build.py", line 626, in run_pymodules_install
  File "pythonforandroid/logger.py", line 175, in shprint
  File "/home/travis/.local/lib/python2.7/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/travis/.local/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/travis/.local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1
.tar.gz                           [0m
           working:     Complete output from command python setup.py egg_info: [0m
           working:     Traceback (most recent call last):                     [0m
           working:       File "<string>", line 1, in <module>                 [0m
           working:       File "/tmp/pip-build-jlmed6/pbkdf2/s...(and 30 more) [0m
           working:         from pbkdf2 import __version__                     [0m
           working:       File "pbkdf2.py", line 62, in <module>               [0m
           working:         from Crypto.Hash import HMAC, SHA as SHA1          [0m
           working:       File "/home/travis/build/AndreMiras...(and 145 more) [0m
           working:         import MD5, BLAKE2s                                [0m
           working:       File "/home/travis/build/AndreMiras...(and 148 more) [0m
           working:         """)                                               [0m
           working:       File "/home/travis/build/AndreMiras...(and 167 more) [0m
           working:         raise OSError("Cannot load native ...(and 20 more) [0m
           working:     OSError: Cannot load native module 'Cr...(and 19 more) [0m
           working:     ----------------------------------------               [0m
           working: [31mCommand "python setup.py egg_info" f...(and 60 more)  [0m
                                                                               
[0m[1;31m# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=pywallet --bootstrap=sdl2 --requirements=hostpython2,kivy,setuptools,openssl,pysha3,ethash,scrypt,bitcoin,rlp,repoze.lru,PyYAML,https://github.com/ethereum/pyethereum/archive/0ae64823d1bccba9c8148adb462060cb83c08f06.zip,https://github.com/ethereum/pydevp2p/archive/cc68f6d69fa88ffaac6f8483392c37eb9f19d712.zip,gevent,pbkdf2,pycryptodome,https://github.com/ethereum/pyethapp/archive/409331e88a397ce5276c430aff4a8866d413e45d.zip,https://gitlab.com/kivymd/KivyMD/repository/archive.zip?ref=7de5790274a45c4fa2fb9c6fcd875645e536c95b,requests,pyelliptic==1.5.7,cffi,secp256k1,qrcode --arch armeabi-v7a --copy-libs --local-recipes /home/travis/build/AndreMiras/PyWallet/src/python-for-android/recipes --color=always --storage-dir=/home/travis/build/AndreMiras/PyWallet/.buildozer/android/platform/build[0m
[0m[1;31m# [0m
[0m[1;31m# Buildozer failed to execute the last command[0m
[0m[1;31m# The error might be hidden in the log above this error[0m
[0m[1;31m# Please read the full log, and search for it before[0m
[0m[1;31m# raising an issue with buildozer itself.[0m
[0m[1;31m# In case of a bug report, please add a full log with log_level = 2[0m

travis_time:end:27f846b6:start=1498344305016112501,finish=1498345317397764167,duration=1012381651666
[0K
[32;1mThe command "./travis/script_android.sh" exited with 0.[0m```

Also another problem is that the build is still shown as green even though there's an error.

**Comment by AndreMiras** [comment]
It's a pain I can't reproduce on my local VM. I'm going to give a try with an Ubuntu Precise VM.
Also I guess we could workaround by updating `pbkdf2/setup.py` or `pbkdf2/pbkdf2.py` so that it doesn't try to import Crypto during the setup.py phase. Since it only needs to access to the `__version__` string.
Or we could totally skip the setup and just deploy `pbkdf2.py` to `site-packages/`.
At first I though we could fix it just by installing pbkdf2 before pycryptodome, but it doesn't seem to be possible by the way buildozer works. Since it seems to be installing recipes before regular packages and pycryptodome is a recipe.
So now, why doesn't it fail on other environment but just fails on Travis? Maybe the host crypto module gets picked up first. Let's find out!

**Comment by AndreMiras** [comment]
Great I could reproduce in a Precise VM.
But this is so legacy, so I gave Travis Trusty a try and it could compile Android dependencies for the minimal reproduction case, so it sounds good.
However now the `script_linux.sh` build is failing. See error below:
```
I/usr/include/python2.7 -c /tmp/pip-build-jS9YZN/Kivy/kivy/graphics/opengl.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-jS9YZN/Kivy/kivy/graphics/opengl.o
    In file included from /tmp/pip-build-jS9YZN/Kivy/kivy/graphics/opengl.c:435:0:
    /tmp/pip-build-jS9YZN/Kivy/kivy/include/gl_redirect.h:64:22: fatal error: GL/gl.h: No such file or directory
     #   include <GL/gl.h>
                          ^
    compilation terminated.
     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/travis/build/AndreMiras/PyWallet/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jS9YZN/Kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-LsNcnO-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/build/AndreMiras/PyWallet/venv/include/site/python2.7/Kivy" failed with error code 1 in /tmp/pip-build-jS9YZN/Kivy/
The command "./travis/script_linux.sh" exited with 1.
```
That should be an easy fix.
